# Numpy for AI/ML-conceptual & Technical Assessment 
## Module 3
# Name: Ganta Tejaswini


In [1]:
import numpy as np

# Section-A : Conceptual Understanding


A1. Why are NumPy arrays generally preferred over Python lists for numerical computation in AI/ML?

NumPy arrays are preferred because they are faster and more memory-efficient for numerical calculations. They support vectorized operations, so we can perform calculations on many values without writing explicit Python loops. NumPy also provides many mathematical and statistical functions that are useful in AI/ML.

In [18]:
#A1 code:
import numpy as np 
    
arr = np.array([10,20,30])
print(arr * 2)

[20 40 60]


A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Vectorization means performing an operation on an entire NumPy array at once instead of processing each element using a Python loop. NumPy performs these operations efficiently using optimized internal code. This can make calculations much faster, especially when working with large datasets. It also makes the code shorter and easier to read.

In [19]:
import numpy as np

x=np.array([1,2,3,4,5])
result = x * 10

print(result)

[10 20 30 40 50]


A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

"A * B" performs element-wise multiplication, meaning corresponding elements of the two arrays are multiplied. In a neural network, element-wise multiplication can be used for applying masks or element-wise operations on data. "A @ B" performs matrix multiplication and combines rows and columns according to matrix multiplication rules. It is commonly used to calculate the weighted sum between an input matrix and a weight matrix in a neural network.

In [20]:
import numpy as np 

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("A * B:")
print(A * B)

print("A @ B:")
print(A @ B)

A * B:
[[ 5 12]
 [21 32]]
A @ B:
[[19 22]
 [43 50]]


A4. What is broadcasting in NumPy?

Broadcasting is a NumPy feature that allows arrays with compatible different shapes to be used together in element-wise operations. NumPy compares their dimensions from the last dimension toward the first. Two dimensions are compatible when they are equal or when one of them is 1. This allows operations between arrays without manually changing their shapes.

In [21]:
import numpy as np 

a = np.array([1,2,3])
b=10

print(a + b)

[11 12 13]


A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

"flatten()" converts an array into a 1D array and normally creates a copy of the data. "ravel()" also returns a 1D representation but tries to return a view of the original data when possible. Therefore, "ravel()" generally uses less additional memory. For a memory-constrained application processing large images, I would prefer "ravel()" when its view behavior is suitable.

In [22]:
import numpy as np 

arr = np.array([[1,2],
                [3,4]])

print("Flatten:", arr.flatten())
print("Ravel:", arr.ravel())


Flatten: [1 2 3 4]
Ravel: [1 2 3 4]


A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function.

For a 2D array, "axis=0" performs the operation down the rows, producing a result for each column. "axis=1" performs the operation across the columns, producing a result for each row. For example, for "[[1,2],[3,4]]", "np.sum(array, axis=0)" gives "[4,6]". "np.sum(array, axis=1)" gives "[3,7]"

In [23]:
import numpy as np
arr = np.array([[1,2],
                [3,4]])

print("axis=0:", np.sum(arr, axis=0))
print("axis=1:", np.sum(arr, axis=1))

axis=0: [4 6]
axis=1: [3 7]


A7. Why is it important to normalize or standardize numerical features before training most ML models?

Normalization or standardization puts numerical features on comparable scales. This is important because features with very large values can have a greater influence on some ML algorithms. Normalization usually scales values to a fixed range such as 0 to 1. Standardization transforms values using the mean and standard deviation so that they are centered around 0 with a standard deviation of 1.


In [24]:
import numpy as np

x = np.array([10, 20, 30, 40, 50])

normal = (x - x.min()) / (x.max() - x.min())
standard = (x - x.mean()) / x.std()

print("Normalization:",normal)
print("Standardization:",standard)

Normalization: [0.   0.25 0.5  0.75 1.  ]
Standardization: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


A8. Why do functions such as np.nanmean() exist?

"np.nanmean()" calculates the mean while ignoring "NaN" values. If "np.mean()" is directly applied to an array containing "NaN", the result will normally be "NaN". Therefore, "np.nanmean()" is useful when missing numerical values are present and we want to calculate the mean of the available values.

In [25]:
import numpy as np

data = np.array([10, 20, np.nan, 40])

print("Mean:", np.mean(data))
print("NaN Mean:", np.nanmean(data))

Mean: nan
NaN Mean: 23.333333333333332


A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images.

For normal ML data, "X.shape = (samples, features)" represents the number of samples and features. For RGB images, we additionally need height, width, and color channels. Therefore, a batch of 64 RGB images with size 128 × 128 has the shape "(64, 128, 128, 3)". Here, 3 represents the RGB channels.


In [26]:
import numpy as np

images = np.zeros((64, 128, 128, 3))

print(images.shape)

(64, 128, 128, 3)


A10. Why is reproducibility important during model development and experimentation?

Reproducibility means getting the same results when an experiment is repeated under the same conditions. Random operations can produce different results each time, which can make experiments difficult to compare. Using "np.random.default_rng(seed)" with a fixed seed makes the generated random values repeatable. This helps in debugging, testing, and comparing model experiments fairly.

In [27]:
import numpy as np

rng1 = np.random.default_rng(10)
rng2 = np.random.default_rng(10)

a = rng1.random(5)
b = rng2.random(5)

print(a)
print(b)
print(np.array_equal(a, b))

[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462]
[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462]
True


# Section-B : Predict The Output

In [9]:
# B1 - Shapes
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

print((a + b).shape)

(3, 3)


In [10]:
# B2 - Slicing
import numpy as np 

x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


In [11]:
# B3 - Boolean Filtering
import numpy as np 

arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

[10 20]


In [12]:
# B4 - Matrix Multiplication
import numpy as np

m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

[[10 14]
 [14 20]]


In [13]:
# B5 - NaN
import numpy as np

data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


In [14]:
# B6 - np.Where()
import numpy as np

x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


In [15]:
# B7 - ndim, size
import numpy as np

a = np.zeros((3, 4))
print(a.ndim)
print(a.size)

2
12


In [17]:
# B8 - Reverse Slicing
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Section-C : Coding / Implementation

In [ ]:
# C1 - pass/fail using np.where()

import numpy as np

scores = np.array([35, 45, 67, 28, 90, 40])

labels = np.where(scores >= 40, "P", "F")

print(labels)

['F' 'P' 'P' 'F' 'P' 'P']


In [19]:
# C2 - Standardize a 1D array

import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
# C3 - Combine Two Batches

import numpy as np

batch1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

batch2 = np.array([
    [7, 8],
    [9, 10]
])

combined = np.vstack((batch1, batch2))

print(combined)
print("Shape:", combined.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape: (5, 2)


In [21]:
# C4 - Standardize X with shape (100, 5)

import numpy as np

X = np.random.default_rng(10).random((100, 5))

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print("Original shape:", X.shape)
print("Standardized shape:", X_standardized.shape)
print("Mean:", np.mean(X_standardized, axis=0))
print("Standard deviation:", np.std(X_standardized, axis=0))

Original shape: (100, 5)
Standardized shape: (100, 5)
Mean: [-2.46469511e-16 -5.05429032e-16  6.23945340e-16  3.64153152e-16
 -5.10702591e-17]
Standard deviation: [1. 1. 1. 1. 1.]


In [22]:
# C6 - Calculate y_pred and MSE

import numpy as np

X = np.array([
    [1, 2],
    [2, 3],
    [3, 4]
])

w = np.array([2, 3])
b = 1

y_true = np.array([7, 12, 17])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 9 14 19]
MSE: 4.0


In [23]:
# C7 - Min-max normalization of a grayscale image

import numpy as np

image = np.array([
    [0, 50, 100],
    [150, 200, 255]
])

normalized = (image - image.min()) / (image.max() - image.min())

print("Original image:")
print(image)

print("Normalized image:")
print(normalized)

Original image:
[[  0  50 100]
 [150 200 255]]
Normalized image:
[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


In [24]:
# C8 - Average pixel value of each RGB image 

import numpy as np

images = np.random.default_rng(10).random((4, 28, 28, 3))

average = np.mean(images, axis=(1, 2, 3))

print("Batch shape:", images.shape)
print("Average of each image:", average)
print("Result shape:", average.shape)

Batch shape: (4, 28, 28, 3)
Average of each image: [0.4989943  0.50477468 0.5037493  0.50337323]
Result shape: (4,)


# Section-D : Applied / Scenario Based - Problems

In [36]:
# D1-A : Create data containing NaN

import numpy as np

data = np.array([
    [10.0, 20.0, np.nan],
    [30.0, 40.0, 50.0],
    [60.0, np.nan, 80.0]
])

print("Original data:")
print(data)
print("\n")


# B : Detect missing values

missing = np.isnan(data)

print("Missing value locations:")
print(missing)

print("Total missing values:", np.sum(missing))
print("\n")


# C : Handle missing values

column_mean = np.nanmean(data, axis=0)

rows, columns = np.where(np.isnan(data))

clean_data = data.copy()

clean_data[rows, columns] = column_mean[columns]

print("Clean data:")
print(clean_data)
print("\n")


# D : Standardize the clean data

mean = np.mean(clean_data, axis=0)
std = np.std(clean_data, axis=0)

standardized = (clean_data - mean) / std

print("Standardized data:")
print(standardized)

Original data:
[[10. 20. nan]
 [30. 40. 50.]
 [60. nan 80.]]


Missing value locations:
[[False False  True]
 [False False False]
 [False  True False]]
Total missing values: 2


Clean data:
[[10. 20. 65.]
 [30. 40. 50.]
 [60. 30. 80.]]


Standardized data:
[[-1.13554995 -1.22474487  0.        ]
 [-0.16222142  1.22474487 -1.22474487]
 [ 1.29777137  0.          1.22474487]]


D2 – 1 RGB Image and Batch of RGB Images

An RGB image has 3 color channels: Red, Green, and Blue. A single image of size 64×64 pixels is represented as (64, 64, 3).
A batch of RGB images means multiple images are grouped together. For 16 images, the shape is (16, 64, 64, 3), where 16 represents the number of images.

In [41]:
# D2 - 1: RGB Image and Batch RGB Images

# Single Image RGB

image_shape = (64, 64, 3)
print(image_shape)

# Batch Images RGB

batch_shape = (16, 64, 64, 3)

print(batch_shape)
print("\n")

# 2 : Creating the image batch

import numpy as np

rng = np.random.default_rng(10)

images = rng.integers(
    0, 256,
    size=(16, 64, 64, 3)
)

print("Batch shape:", images.shape)
print("\n")

# 3 : Calculate average image

average_image = np.mean(images, axis=0)

print("Average image shape:", average_image.shape)

(64, 64, 3)
(16, 64, 64, 3)


Batch shape: (16, 64, 64, 3)


Average image shape: (64, 64, 3)


#D3 : Debug the Model Code

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0, 0.2])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)


Bug 1 : Weight shape

print(X.shape)
print(w.shape)
w = np.array([0.5, 1.0])

Bug 2 : MSE formula

the original:
np.mean(y_true - y_pred ** 2)

Corrected One:

np.mean((y_true - y_pred) ** 2)

In [44]:
# D3 - Corrected Code

import numpy as np

X = np.array([
    [1, 2],
    [2, 3],
    [3, 4]
])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("X shape:", X.shape)
print("w shape:", w.shape)
print("Predicted values:", y_pred)
print("MSE:", mse)

X shape: (3, 2)
w shape: (2,)
Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


# Section-E : Bonus / Challenge

In [45]:
# E1 - Per-Column Min–Max Normalization

import numpy as np

X = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])

X_min = X.min(axis=0)
X_max = X.max(axis=0)

normalized = (X - X_min) / (X_max - X_min)

print(normalized)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [46]:
# E2 - Three-Level Score Classification

import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
